version: '3.1'

services:
    zookeeper:
        image: zookeeper
        container_name: zookeeper
        restart: always
        ports:
            - 2181:2181
    cassandra:
       image: cassandra
       container_name: cassandra
       restart: always
       ports:
           - 9042:9042
       environment:
           CASSANDRA_CLUSTER_NAME: my-cluster
           CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
           CASSANDRA_DC: my-datacenter
    kafka:
        image: wurstmeister/kafka
        container_name: kafka
        depends_on:
            - zookeeper
        links:
            - zookeeper
        restart: always
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ADVERTISED_HOST_NAME: 172.19.0.1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

